"""Reusable build and runtime support for Obvious One plugin distributions."""

from .contract import (
    AssetGroup,
    ContentRule,
    ContractError,
    DistributionContract,
    PublicationProfile,
    PublicationTarget,
    RagProfile,
    RedistributionEvidence,
    load_contract,
    require_buildable_contract,
    validate_contract,
)
from .verification import (
    ALLOWED_PLACEHOLDERS,
    RESULT_STATES,
    ApplicationConfig,
    ApplicationVerificationProfile,
    CodexBuildProfile,
    ExpansionContext,
    GateResult,
    MarketplaceProfile,
    ProvenanceInventoryRule,
    ProvenanceProfile,
    VerificationCommand,
    VerificationConfigError,
    aggregate_state,
    discover_applications,
    expand_argv,
    load_application_config,
    resolve_within,
    select_applications,
)
from .provenance import (
    ProvenanceError,
    build_provenance,
    inventory_source,
    validate_provenance,
)
from .contract_migration import (
    MigrationProposal,
    build_migration_proposal,
    write_migration_proposal,
)
from .content_policy import (
    ContentPolicyError,
    ResolvedContentPolicy,
    resolve_content_policies,
    write_canonical_file,
)
from .results import (
    ArtifactRecord,
    Diagnostic,
    MutationRecord,
    OperationResult,
    ResultStatus,
    load_result,
    operation_result_from_payload,
    result_json,
    result_payload,
)

__all__ = [
    "AssetGroup",
    "ContentRule",
    "ContractError",
    "DistributionContract",
    "PublicationProfile",
    "PublicationTarget",
    "RagProfile",
    "RedistributionEvidence",
    "load_contract",
    "require_buildable_contract",
    "validate_contract",
    "ALLOWED_PLACEHOLDERS",
    "RESULT_STATES",
    "ApplicationConfig",
    "ApplicationVerificationProfile",
    "CodexBuildProfile",
    "ExpansionContext",
    "GateResult",
    "MarketplaceProfile",
    "ProvenanceInventoryRule",
    "ProvenanceProfile",
    "VerificationCommand",
    "VerificationConfigError",
    "aggregate_state",
    "discover_applications",
    "expand_argv",
    "load_application_config",
    "resolve_within",
    "select_applications",
    "ProvenanceError",
    "build_provenance",
    "inventory_source",
    "validate_provenance",
    "MigrationProposal",
    "build_migration_proposal",
    "write_migration_proposal",
    "ContentPolicyError",
    "ResolvedContentPolicy",
    "resolve_content_policies",
    "write_canonical_file",
    "ArtifactRecord",
    "Diagnostic",
    "MutationRecord",
    "OperationResult",
    "ResultStatus",
    "load_result",
    "operation_result_from_payload",
    "result_json",
    "result_payload",
]

__version__ = "0.1.0"
